version: "3.9"

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "9999:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]

  mongo-init-replica:
    image: mongodb/mongodb-community-server:latest
    depends_on:
      - mongodb
    entrypoint: >
      bash -c "
      echo 'Waiting for MongoDB to be ready...' &&
      until mongosh --host mongodb --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do
        sleep 1;
      done &&
      echo 'Initializing replica set...' &&
      mongosh --host mongodb --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [{ _id: 0, host: \"mongodb:27017\" }]
        })
      ' || echo 'Replica set already initialized'
      "
volumes:
  mongodb_data:
